<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="base" params="length width height mass wheel_radius wheel_pos_z namespace">
    <link name="${namespace}_footprint"/>

    <link name="${namespace}_base_link">
      <visual>
        <origin xyz="-0.15 0.1 0" rpy="0 0 -1.57"/>
        <geometry>
          <!--box size="${length} ${width} ${height}"/-->
          <mesh scale="0.001 0.001 0.001" filename="file:///home/ubu/linorobot2_ws/src/linorobot2/linorobot2_description/meshes/layer_1_solidworks.STL"/>

          <!-- <mesh filename="" scale="0.001 0.001 0.001"/> -->
        </geometry>
        <material name="yellow">
          <color rgba="0.8784 0.6627 0.6627 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * ((width  * width)  + (height * height))}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * ((length * length) + (height * height))}" iyz="0.0"
                 izz="${(1/12) * mass * ((length * length) + (width  * width))}"/>
      </inertial>
    </link>

    <gazebo reference="${namespace}_base_link">
      <visual>
        <material>
          <ambient>0.8392 0.6314 0.0 1.0</ambient>
          <diffuse>0.8392 0.6314 0.0 1.0</diffuse>
          <specular>0.99 0.99 0.99 1.0</specular>
          <emissive>0.0 0.0 0.0 0.0</emissive>
        </material>
      </visual>
    </gazebo>

    <joint name="${namespace}_base_to_footprint" type="fixed">
      <parent link="${namespace}_footprint"/>
      <child link="${namespace}_base_link"/>
      <origin xyz="0 0 ${wheel_radius - wheel_pos_z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
</robot>
