<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="base" params="length width height mass
   wheel_radius wheel_pos_z base_origo_offset caster_diameter">
    
    
    <link name="base_link"/>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.105 0 0"/>
    </joint>

      <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>


    <link name="base_footprint"/>


    <link name="chassis">
      <visual>
        <origin xyz="0 0 ${caster_diameter/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <material name="yellow">
          <color rgba="0.8784 0.6627 0.6627 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * (width  * 2 + height * 2)}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * (length * 2 + height * 2)}" iyz="0.0"
                 izz="${(1/12) * mass * (length * 2 + width * 2)}"/>
      </inertial>
    </link>

    <gazebo reference="base_link">
      <visual>
        <material>
          <ambient>0.8392 0.6314 0.0 1.0</ambient>
          <diffuse>0.8392 0.6314 0.0 1.0</diffuse>
          <specular>0.99 0.99 0.99 1.0</specular>
          <emissive>0.0 0.0 0.0 0.0</emissive>
        </material>
      </visual>
    </gazebo>

  </xacro:macro>
</robot>
