<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="layer2" params="length width height mass wheel_radius wheel_pos_z">
   <link name="layer_2">
      <visual>
        <origin xyz="0 -0.0015 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <material name="Grey"/>
      </visual>


      <collision>
        <origin xyz="0 -0.0015 0" rpy="0 0 0"/>
        <geometry>
          <box size="-${length} ${width} ${height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="base_to_layer2" type="fixed">
      <parent link="base_link"/>
      <child link="layer_2"/>
      <origin xyz="0 0 ${(wheel_radius - wheel_pos_z)+0.07}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
</robot>